### ISSUE TITLE
Nickname verification

### ISSUE THREAD

**Issue by elona6869** [Azuriom/Plugin-Vote#91] opened 2024-05-20 09:36 UTC
hello I come to ask you if it is possible to add the possibility to activate or deactivate the verification of the nickname to the selection of the nickname on the site
no need to nlogin or authme just disable the verification of nicknames

**Comment by MrMicky-FR** [comment] 2024-05-20 10:10
Duplicate of #19

**Closed by MrMicky-FR** 2024-05-20 10:10 UTC
Labels: duplicate
